### ISSUE TITLE
The Latest BungeeCord Can't Get the True IP with This Plugin

### ISSUE THREAD

**Issue by Xuwznln** [MinelinkNetwork/BungeeProxy#2]

**Comment by Byteflux** [comment]
I'm fairly certain the latest Bungee has this feature now built-in.

**Comment by Xuwznln** [comment]
But the player through Haproxy cant join the server without the plugin. It shows "Disconnected".

**Comment by Byteflux** [comment]
Yes, Bungee added HAProxy support so you'll probably have to configure it. This plugin is now obsolete and should not be run with the recent Bungee versions.

I do not use the latest Bungee, I can't help you with how to configure it.

**Comment by Xuwznln** [comment]
OK.Thanks.
